### ISSUE TITLE
[TODO] IU봇 v2 업데이트 지원

### ISSUE THREAD

**Issue by wonderlandpark** [koreanbots/koreanbots#136]
## TODO

- [x] approve 기능 (DB구조 변경에 따른 수정 필요)
- [x] deny 기능 (거부 사유를 DB에 포함함에 따라 수정 필요)
- [x] report 기능 (신고의 빠른 처리(답변)를 위한 새로운 명령어 추가
- [x] todo 기능 개선

**Comment by kijk2869** [comment]
- [ ] 봇 삭제시 자동 추방
